
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/jetbrains/clion-2023.2.2/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 6.6.3-1-default - x86_64
...
